name: Python application

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11.0
        uses: actions/setup-python@v1
        with:
          python-version: 3.11.0
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Generate coverage report
        run: |
          pytest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true